/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppGallery {
        "slidesComponent": any;
    }
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface SafeMoonCycle {
    }
}
declare global {
    interface HTMLAppGalleryElement extends Components.AppGallery, HTMLStencilElement {
    }
    var HTMLAppGalleryElement: {
        prototype: HTMLAppGalleryElement;
        new (): HTMLAppGalleryElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLSafeMoonCycleElement extends Components.SafeMoonCycle, HTMLStencilElement {
    }
    var HTMLSafeMoonCycleElement: {
        prototype: HTMLSafeMoonCycleElement;
        new (): HTMLSafeMoonCycleElement;
    };
    interface HTMLElementTagNameMap {
        "app-gallery": HTMLAppGalleryElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "safe-moon-cycle": HTMLSafeMoonCycleElement;
    }
}
declare namespace LocalJSX {
    interface AppGallery {
        "slidesComponent"?: any;
    }
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface SafeMoonCycle {
    }
    interface IntrinsicElements {
        "app-gallery": AppGallery;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "safe-moon-cycle": SafeMoonCycle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-gallery": LocalJSX.AppGallery & JSXBase.HTMLAttributes<HTMLAppGalleryElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "safe-moon-cycle": LocalJSX.SafeMoonCycle & JSXBase.HTMLAttributes<HTMLSafeMoonCycleElement>;
        }
    }
}
